services:
  backend:
    container_name: noteapp-backend-build
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app

  frontend:
    container_name: noteapp-frontend-build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - API_URL=http://54.234.164.178:5000
    volumes:
      - ./frontend:/usr/share/nginx/html

  mongo:
    container_name: noteapp-mongo-build
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_build:/data/db

volumes:
  mongo_data_build:
