version: '3.8'

services:
  backend:
    container_name: noteapp-backend-build
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-5000}:5000"  # fallback default
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    working_dir: /app

  frontend:
    container_name: noteapp-frontend-build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-80}:80"  # fallback default
    environment:
      - API_URL=http://localhost:5000
    volumes:
      - ./frontend:/usr/share/nginx/html

  mongo:
    container_name: noteapp-mongo-build
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_build:/data/db

volumes:
  mongo_data_build:
